{
"version":3,
"file":"CompletionException.impl.java.js",
"lineCount":45,
"mappings":"A;;;;;;;MAEa,mB;;CAAA,W;EAAAA,Q;;;;QACJ,8C,gBAA2BC,O,mBAAmBC,K;EAA9CC,8B;EAAAA,0C;EAAAA,uH;EAAAA,yF;EAAAA,iB;;;;CAAA,4F,gBAA2BF,O,mBAAmBC,K;EACnDE,oG;;;;QAGK,4B,kBAA8BF,K;EAA9BC,8B;EAAAA,0C;EAAAA,4F;EAAAA,yF;EAAAA,iB;;;;CAAA,0E,kBAA8BD,K;EACnCE,yE;;;QANS,O;EAAAC,sC;EAAAA,mC;EAAAA;",
"sources":["CompletionException.java"],
"names":["java.util.concurrent.CompletionException.<synthetic: ctor_js>","message","cause","java.util.concurrent.CompletionException.<synthetic: ctor_create>","java.util.concurrent.CompletionException.<init>","java.util.concurrent.CompletionException.<clinit>"]
}
